const CHANGE_TOP_BNNAER = 'recommend/CHANGE_TOP_BNNAER'
const CHANGE_HOT_RECOMMEND = 'recomend/CHANGE_HOT_RECOMMEND'
const CHANGE_NEW_DISC = 'recomend/CHANGE_NEW_DISC'
const CHANGE_RANKING_LIST_NEW = 'recomend/CHANGE_RANKING_LIST_NEW'
const CHANGE_RANKING_LIST_HOT = 'recomend/CHANGE_RANKING_LIST_HOT'
const CHANGE_RANKING_LIST_ORIGIN = 'recomend/CHANGE_RANKING_LIST_ORIGIN'
const CHANGE_RIGHT_LIST='recomend/CHANGE_RIGHT_LIST'


// eslint-disable-next-line
export default {
  CHANGE_TOP_BNNAER,
  CHANGE_HOT_RECOMMEND,
  CHANGE_NEW_DISC,
  CHANGE_RANKING_LIST_NEW,
  CHANGE_RANKING_LIST_HOT,
  CHANGE_RANKING_LIST_ORIGIN,
  CHANGE_RIGHT_LIST
}
